### PR TITLE
Enable strict + fix `strictNullCheck` TS errors

### PR DESCRIPTION
**Pull request by colinking**
This PR fixes an issue seen by Typewriter-users where the optional types introduced in https://github.com/segmentio/typewriter/pull/39 cause `strictNullChecks` errors during builds:

```
integrations?: {
    All?: boolean
    AppsFlyer?: {
      appsFlyerId: string
    }
    // Adds `| undefined`
    [key: string]: boolean | { [key: string]: string } | undefined
}
```

```
#!/bin/bash -eo pipefail
yarn build
yarn run v1.6.0
$ make build
./node_modules/.bin/tsc && rsync -am --include='*.graphql' --include='*/' --exclude='*' src dist
src/lib/typewriter/generated/index.d.ts:54:5 - error TS2411: Property 'All' of type 'boolean | undefined' is not assignable to string index type 'boolean | { [key: string]: string; }'.

54     All?: boolean;
       ~~~

src/lib/typewriter/generated/index.d.ts:55:5 - error TS2411: Property 'AppsFlyer' of type '{ appsFlyerId: string; } | undefined' is not assignable to string index type 'boolean | { [key: string]: string; }'.

55     AppsFlyer?: {
       ~~~~~~~~~


Found 2 errors.
```

This PR also enables `strict` on this codebase.

### CODE REVIEW

File: examples/gen-js/ts/pages/index.tsx [hunk 1]
```diff
@@ -39,12 +39,12 @@ export default class extends React.Component<any> {
...
           }
           {
-            photos.map((id) => (
+            photos.map((id: string) => (
               <div key={id} className='photo'>
                 <a
                   className='photoLink'
                   href={`/photo?id=${id}`}
-                  onClick={(e) => this.showPhoto(e, id)}
+                  onClick={(e: React.MouseEvent<HTMLAnchorElement>) => this.showPhoto(e, id)}
```
Comment (gurdasnijor) [inline examples/gen-js/ts/pages/index.tsx]: Figured this would be in the React typedef 🤔
